### ISSUE TITLE
Waar blijft die code?

### ISSUE THREAD

**Issue by marcvdm** [JakeNierop/Framework#2]
Waar blijft die code dan? Meters maken!!!!!!!!

**Comment by JakeNierop** [comment]
I'm on it!

**Comment by bnierop** [comment]
Okee ik wacht op de commits! Ik kijk mee, maar ze zijn er nog niet!

**Comment by JakeNierop** [comment]
He bro! Mark en ik zijn bezig geweest en er zijn dingen gecommit.


Sent from my iPhone

On 27 Dec 2016, at 14:37, bnierop <notifications@github.com<mailto:notifications@github.com>> wrote:


Okee ik wacht op de commits! Ik kijk mee, maar ze zijn er nog niet!

-
